runtime: go112

main: ./main

handlers:
  - url: /static
    static_dir: static

  - url: /static/js
    static_dir: static/js

  - url: /static/css
    static_dir: static/css

  - url: /.*
    script: auto